template-file-path: >-
  fileserver-demo/ssm-automation/cfn-create-ssm-automation-secretmanager-adjoin.yml
parameters:
  SSMAutomationRunbookNameParam: DomainJoinAutomation
  ADDomainNameParam: fileserver-demo.cloud
  ADUserNameParam: FILESERVER-DEMO\Admin
  ADPasswordParam: Password123
  ADTargetOUParam: OU=Computers,dc=fileserver-demo,dc=cloud
tags: {}
